services:
  postgres:
    image: postgres:15
    container_name: banbok-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: banbok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
