services:
  redis:
    image: redis:7-alpine
    container_name: banbok-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - banbok-network
    command: redis-server --appendonly yes

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: banbok-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - banbok-network

volumes:
  redis_data:

networks:
  banbok-network:
    driver: bridge
