name: Deploy Backend to GCP

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
      - 'packages/**'
      - 'cloudbuild.yaml'
      - '.github/workflows/deploy.yml'
  
  # Manual trigger
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: banbok-backend
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker
        
      - name: Build and push Docker image
        run: |
          docker build -f apps/backend/Dockerfile -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 3001 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 10 \
            --set-env-vars NODE_ENV=production \
            --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --set-env-vars JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --set-env-vars CORS_ORIGIN="${{ secrets.CORS_ORIGIN }}" \
            --set-env-vars FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            --set-env-vars NAVER_CLIENT_ID="${{ secrets.NAVER_CLIENT_ID }}" \
            --set-env-vars NAVER_CLIENT_SECRET="${{ secrets.NAVER_CLIENT_SECRET }}" \
            --set-env-vars NAVER_CALLBACK_URL="${{ secrets.NAVER_CALLBACK_URL }}" \
            --set-env-vars SMTP_HOST="${{ secrets.SMTP_HOST }}" \
            --set-env-vars SMTP_USER="${{ secrets.SMTP_USER }}" \
            --set-env-vars SMTP_PASS="${{ secrets.SMTP_PASS }}" \
            --quiet
            
      - name: Get service URL
        run: |
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)')
          echo "🚀 Deployment successful!"
          echo "Service URL: $SERVICE_URL"